telegram bot balance check
multiversx/mx-chain-tools-go pull request #7
Opened 2021-10-18 08:52 UTC by miiu96

2022-07-22 08:29 UTC, bogdan-rosianu commented on tgbot/cmd/bot/config.toml
> +        apiKey = ""
empty line + replace address + gatewayURL

2022-07-22 08:31 UTC, miiu96 commented on tgbot/cmd/bot/config.toml
> +        apiKey = ""
done.

2022-07-22 08:31 UTC, bogdan-rosianu approved these changes

2023-08-04 12:05 UTC, bogdan-rosianu requested changes

2023-08-04 12:05 UTC, bogdan-rosianu commented on tgbot/cmd/bot/main.go
> +	logger "github.com/ElrondNetwork/elrond-go-logger"
rebrand the imports

2023-08-04 12:05 UTC, bogdan-rosianu commented on tgbot/process/notifier.go
> +func NewBalanceNotifier(cfg *config.GeneralConfig) (*notifier, error) {
add comment

2023-08-04 12:05 UTC, bogdan-rosianu commented on tgbot/process/notifier.go
> +func (n *notifier) StartNotifier() {
add comment

2023-08-04 12:05 UTC, bogdan-rosianu commented on tgbot/process/balance.go
> +func GetAddressBalance(gatewayURL string, address string) (*big.Int, error) {
add comment

2023-08-04 12:05 UTC, bogdan-rosianu commented on tgbot/config/config.go
> +type GeneralConfig struct {
add comment

2023-08-07 09:33 UTC, miiu96 commented on tgbot/cmd/bot/main.go
> +	logger "github.com/ElrondNetwork/elrond-go-logger"
done

2023-08-07 09:34 UTC, miiu96 commented on tgbot/process/notifier.go
> +func NewBalanceNotifier(cfg *config.GeneralConfig) (*notifier, error) {
added

2023-08-07 09:34 UTC, miiu96 commented on tgbot/process/notifier.go
> +func (n *notifier) StartNotifier() {
added

2023-08-07 09:34 UTC, miiu96 commented on tgbot/process/balance.go
> +func GetAddressBalance(gatewayURL string, address string) (*big.Int, error) {
added

2023-08-07 09:35 UTC, miiu96 commented on tgbot/go.mod
> +go 1.15
done

2023-08-07 09:44 UTC, bogdan-rosianu commented on tgbot/process/notifier.go
> +		telegramBotKey:  cfg.Telegram.ApiKey,
remove empty line (L54)

2023-08-07 09:44 UTC, bogdan-rosianu commented on tgbot/process/notifier.go
> +	defer n.safeCloser.Close()
could remove `defer`

2023-08-07 10:08 UTC, miiu96 commented on tgbot/process/notifier.go
> +		telegramBotKey:  cfg.Telegram.ApiKey,
done

2023-08-07 10:09 UTC, miiu96 commented on tgbot/process/notifier.go
> +	defer n.safeCloser.Close()
done

2023-08-07 10:26 UTC, bogdan-rosianu approved these changes

2023-08-07 10:50 UTC, schimih approved these changes

2023-08-07 11:14 UTC, merged